version: "2"

linters:
  default: none
  enable:
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace

  # Do not enable:
  # - wsl       (too opinionated about newlines)
  # - godox     (todos are OK)
  # - bodyclose (false positives on helper functions)
  # - prealloc  (not worth it in scope of this project)
  # - funlen    (gocyclo is enough)
  # - gochecknoglobals (we know when it is ok to use globals)

  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - exitAfterDefer
        - whyNoLint
        - singleCaseSwitch
        - commentedOutCode
        - appendAssign
        - octalLiteral
        - preferWriteByte
        - httpNoBody
        - preferFprint
      settings:
        ruleguard:
          failOn: dsl,import
          rules: '${base-path}/gorules/rules.go'
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true

  exclusions:
    generated: lax
    rules:
      # Exclude go:generate from lll.
      - linters: [lll]
        source: '//go:generate'

      # Disable linters that are annoying in tests.
      - path: _test\.go
        linters:
          - dupl
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - lll

      # Ignore shadowing of err, ctx and log.
      - linters: [govet]
        text: 'declaration of "(err|ctx|log)"'

      # Ignore linters in main packages.
      - path: cmd\/.+\/main\.go
        linters: [funlen, gocognit, goconst, gocyclo]

      # Intended in commands:
      # G307: Deferring unsafe method "Close" on type "*os.File"
      # G304: Potential file inclusion via variable
      - path: cmd\/.+\/main\.go
        text: G(307|304)

      # Package comments are not required in internal packages.
      - path: internal
        linters: [revive]
        text: package-comments

      - linters: [staticcheck]
        text: 'SA1019: telegram.+ is deprecated:'

      - linters: [revive]
        text: 'if-return: redundant if ...; err != nil check, just return error instead.'
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/gotd/
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
