# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2
project_name: teled
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - riscv64
    ignore:
      # riscv64 is only supported on linux.
      - goos: windows
        goarch: riscv64
      - goos: darwin
        goarch: riscv64
    main: ./cmd/teled
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore(dep):'
      - '^test:'
nfpms:
  - package_name: teled
    homepage: https://github.com/gotd/teled
    maintainer: The GoTD Authors
    description: Testing Telegram Server in Go
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: ./init/teled.service
        dst: /usr/lib/systemd/system/teled.service
      - src: ./init/teled.env
        dst: /etc/teled/teled.env
        type: "config|noreplace"
        file_info:
          mode: 0640
          owner: root
          group: teled
      - dst: /var/lib/teled
        type: dir
        file_info:
          mode: 0750
          owner: teled
          group: teled
    scripts:
      preinstall: ./scripts/preinstall.sh
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh
      postremove: ./scripts/postremove.sh